# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u73ed\u7ea7\u540d\u79f0')),
                ('clazz', models.CharField(max_length=128, verbose_name='\u73ed\u7ea7')),
                ('grade', models.CharField(max_length=128, verbose_name='\u5e74\u7ea7')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=1024)),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('answer', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('isCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTopTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('pwd', models.CharField(max_length=128)),
                ('stuNO', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('introduction', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.CharField(max_length=128)),
                ('pwd', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
                'verbose_name_plural': '\u6559\u5e08',
            },
        ),
        migrations.CreateModel(
            name='TestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('testScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('iscount', models.CharField(max_length=128)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(through='ses.Score', to='ses.Subject'),
        ),
        migrations.AddField(
            model_name='seat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STUDENT', to='ses.Student'),
        ),
        migrations.AddField(
            model_name='seat',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SUBJECT', to='ses.Subject'),
        ),
        migrations.AddField(
            model_name='scorerule',
            name='topTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.ScoreTopTitle'),
        ),
        migrations.AddField(
            model_name='score',
            name='scoreRule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.ScoreRule'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Student'),
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='testForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.TestForm'),
        ),
        migrations.AddField(
            model_name='course',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Homework'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ses.Teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(through='ses.Course', to='ses.Subject'),
        ),
    ]
