# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerule',
            name='createTeacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ses.Teacher'),
            preserve_default=False,
        ),
    ]
